services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OPENAI_API_BASE_URL=$OPENAI_API_BASE_URL
      - OPENAI_API_KEY=$OPENAI_API_KEY

volumes:
  open-webui:
    driver: local
